### ISSUE TITLE
Linthesia don't work - Cannot install libgconfmm-2.6-1v5 

### ISSUE THREAD

**Issue by EnterVPL** [allan-simon/linthesia#97]
I tried run linthesia but:
```cmd
linthesia: error while loading shared libraries: libgconfmm-2.6.so.1: cannot open shared object file: No such file or directory
```

I tried instal that -  ``sudo apt-get install libgconfmm-2.6-1v5`` but I got
```cmd
Reading package lists ... Done
Building a dependency tree
Reading status information ... Done
Libgconfmm-2.6-1v5 does not have a version available but is referenced by another package.
Typically, this means that the package is missing, has been replaced with another
package or is not available from the currently set sources.

E: The libgconfmm-2.6-1v5 package is not a candidate for installation
```
Linthesia requires this lib.
I have Ubuntu Studio (**Ubuntu 20 LTS**) **64bit**

What am I supposed to do now?

**Comment by baptx** [comment]
On Lubuntu 20.04, this issue was gone after following the instructions to install dependencies with `sudo aptitude install clang libtool autoconf automake make libsfml-dev librtmidi-dev libgtkmm-2.4-dev libgconfmm-2.6-dev libgtkglextmm-x11-1.2-dev libasound2-dev`, doing `autoreconf -i` and `./configure` before using the `make` command.
However, I cannot compile: https://github.com/allan-simon/linthesia/issues/98
I found a similar open source project with binaries that worked: https://github.com/kosua20/MIDIVisualizer

**Comment by jonadem** [comment]
Someone have a WIP about this in another repository :
https://github.com/laf0rge/linthesia/commit/506b3112a0bd8a332743f91c90a5b45c2a4b78ba

**Comment by allan-simon** [comment]
ah thanks for the link , I've pinged the author to know how his fix is going :)

**Comment by baptx** [comment]
@jonadem thanks, I asked a question about a sound issue, maybe you have an idea: https://github.com/linthesia/linthesia/issues/41#issuecomment-850911873

**Comment by allan-simon** [comment]
my fork is actually a complete rewrite , so less feature but it's based on the SFML / cmake  so it will be easier to build up new feature as I leverage a library made to make games ,  so user input /  screen detection is already a given.

**Comment by allan-simon** [comment]
actually i've just checked but I 'dont use libgconf in my rewrite :facepalm:

**Comment by allan-simon** [comment]
I've removed it from the readme , so now at least it compiles on ubuntu18.04 :)
